### ISSUE TITLE
Reading bgzipped VCF panics with 'range end index 4023724882 out of range for slice of length 65536'

### ISSUE THREAD

**Issue by curoli** [zaeleus/noodles#84]
Hello,

  My code panics trying to read bgzipped VCF files:
  
```
use crate::stats::Stats;
use crate::error::Error;
use noodles::{bgzf, vcf};
use fs_err::File;
use noodles::vcf::Header;

pub(crate) fn read_vcf(file: &str) -> Result<Stats, Error> {
    let mut reader =
        vcf::Reader::new(bgzf::Reader::new(File::open(file)?));
    let header = reader.read_header()?.parse::<Header>()?;  //  panics here
    let sample_ids: Vec<String> = header.sample_names().iter().map(String::from).collect();
    Ok(Stats::new(sample_ids))
}
```

From my Cargo.toml:

```
noodles = { version = "0.22.0", features = ["bgzf", "vcf"] }
```

The stack trace is:

```
thread 'main' panicked at 'range end index 4023724882 out of range for slice of length 65536', /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-bgzf-0.11.0/src/block.rs:23:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::slice::index::slice_end_index_len_fail
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:43:5
   3: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index_mut
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:256:13
   4: core::slice::index::<impl core::ops::index::IndexMut<I> for [T]>::index_mut
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:26:9
   5: noodles_bgzf::block::Block::buffer_mut
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-bgzf-0.11.0/src/block.rs:23:14
   6: noodles_bgzf::reader::read_block
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-bgzf-0.11.0/src/reader.rs:332:25
   7: <noodles_bgzf::reader::Reader<R> as std::io::BufRead>::fill_buf
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-bgzf-0.11.0/src/reader.rs:217:30
   8: noodles_vcf::reader::read_header
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-vcf-0.15.0/src/reader.rs:326:19
   9: noodles_vcf::reader::Reader<R>::read_header
             at /home/oliverr/.cargo/registry/src/github.com-1ecc6299db9ec823/noodles-vcf-0.15.0/src/reader.rs:145:9
  10: phenics::read::read_vcf
             at ./src/read.rs:10:18
  11: phenics::run
             at ./src/lib.rs:19:29
  12: phenics::main
             at ./src/main.rs:4:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
```

The input file is from the Thousand Genomes Project (aka The International Genome Sample Resource) and can be found here:

http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz

Similar panics occur (except at different positions) with other files I tried from IGSR, which are:

http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr22.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz

And it's a blocker. Would be great if this could be fixed soon. Thanks!

Best, Oliver

**Comment by zaeleus** [comment]
Hi, @curoli! Thanks for the report and the sample inputs.

I'm not able to reproduce this issue.

```
$ sha256sum ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
1bbddc1eac3b35d9408bdfb435632126614a7ac89d32d27aa30db6dc94600fec  ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz
$ cargo run --release --all-features --example bgzf_read ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz > /dev/null
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/examples/bgzf_read ALL.chr20.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf.gz`
$ echo $?
0
```

Does running the [`bgzf_read`](https://github.com/zaeleus/noodles/blob/ac2916c6c4c547a266da3313e391a2991e2a8642/noodles-bgzf/examples/bgzf_read.rs) example program also fail for you? I would also check if you're accidentally using the uncompressed VCF as input instead of the bgzipped file.

**Comment by curoli** [comment]
Oh, OK, it's not the fault of noodles.

Apparently the files where first bgzipped, and then in addition, gzipped on top of that. Once I gunzip the files, I get bgzipped files which can be read using noodles.

Thanks for the response, I'm closing the issue.
